version: 2.1

executors:
  base:
    docker:
      - image: cimg/node:20.12.0-browsers

commands:
  prepare-dependencies:
    steps:
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}

      - run:
          name: Install pnpm package manager
          command: |
            sudo corepack enable
            sudo corepack prepare pnpm@latest-9 --activate

      - run:
          name: Install Dependencies
          command: |
            pnpm install

      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules

jobs:
  lint-and-test:
    executor: base

    steps:
      - checkout

      - prepare-dependencies

      - run:
          name: Format Check
          command: |
            pnpm run format:check

      - run:
          name: Run Lint
          command: |
            pnpm run lint --continue

      - run:
          name: Run Stylelint
          command: |
            pnpm run stylelint --continue

      - run:
          name: Run Unit Test
          command: |
            pnpm run test --continue -- --ci --runInBand --coverage

      - run:
          name: Run Integration Unit Test
          command: |
            pnpm run test:integration --continue -- --ci --runInBand

      - store_test_results:
          path: ./reports

      - store_artifacts:
          path: ./coverage

workflows:
  main:
    jobs:
      - lint-and-test
