version: 2.1

executors:
  default:
    docker:
      - image: cimg/node:16.14.0-browsers

orbs:
  nx: nrwl/nx@1.6.1
  codecov: codecov/codecov@3.2.4

commands:
  prepare-dependencies:
    steps:
      - restore_cache:
          keys:
            - v1-yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-yarn-packages-{{ .Branch }}-
            - v1-yarn-packages-

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn

      - save_cache:
          key: v1-yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

jobs:
  agent:
    executor: default

    parameters:
      ordinal:
        type: integer

    steps:
      - checkout

      - prepare-dependencies

      - run:
          name: Start the agent << parameters.ordinal >>
          command: yarn nx-cloud start-agent
          no_output_timeout: 60m

  main:
    executor: default

    environment:
      NX_CLOUD_DISTRIBUTED_EXECUTION: 'true'

    steps:
      - checkout

      - prepare-dependencies

      - nx/set-shas

      - run:
          name: Initialize the Nx Cloud distributed CI run
          command: yarn nx-cloud start-ci-run

      - run:
          name: Run workspace lint
          command: yarn nx-cloud record -- yarn nx workspace-lint

      - run:
          name: Check format
          command: yarn nx-cloud record -- yarn nx format:check --base=$NX_BASE --head=$NX_HEAD

      - run:
          name: Run ESLint
          command: yarn nx affected --base=$NX_BASE --head=$NX_HEAD --target=lint --parallel=3 --configuration=ci

      - run:
          name: Run tests and collect coverage
          command: yarn nx affected --base=$NX_BASE --head=$NX_HEAD --target=test --parallel=3 --ci --code-coverage

      - run:
          name: Stop all agents
          command: yarn nx-cloud stop-all-agents
          when: always

      - store_test_results:
          path: ./reports

      - store_artifacts:
          path: ./coverage

      - codecov/upload:
          file: ./coverage/libs/core/tile/lcov.info
          flags: core

      - codecov/upload:
          file: ./coverage/libs/backend/feature/shared/lcov.info
          flags: backend

      - codecov/upload:
          file: ./coverage/apps/web/lcov.info
          flags: web

workflows:
  version: 2

  main:
    jobs:
      - agent:
          name: Nx Cloud Agent << matrix.ordinal >>
          matrix:
            parameters:
              ordinal: [1, 2, 3]

      - main:
          name: Nx Cloud Main
