import { AbstractTileSet } from './abstract-tile-set';
import {
  Honor,
  HonorTile,
  Rank,
  Suit,
  SuitTile,
  TileModifier,
} from '../../tile';

export class FourPlayersWithoutRed extends AbstractTileSet {
  public constructor() {
    super(
      new SuitTile(Suit.Character, Rank[1], TileModifier.Normal),
      new SuitTile(Suit.Character, Rank[1], TileModifier.Normal),
      new SuitTile(Suit.Character, Rank[1], TileModifier.Normal),
      new SuitTile(Suit.Character, Rank[1], TileModifier.Normal),
      new SuitTile(Suit.Character, Rank[2], TileModifier.Normal),
      new SuitTile(Suit.Character, Rank[2], TileModifier.Normal),
      new SuitTile(Suit.Character, Rank[2], TileModifier.Normal),
      new SuitTile(Suit.Character, Rank[2], TileModifier.Normal),
      new SuitTile(Suit.Character, Rank[3], TileModifier.Normal),
      new SuitTile(Suit.Character, Rank[3], TileModifier.Normal),
      new SuitTile(Suit.Character, Rank[3], TileModifier.Normal),
      new SuitTile(Suit.Character, Rank[3], TileModifier.Normal),
      new SuitTile(Suit.Character, Rank[4], TileModifier.Normal),
      new SuitTile(Suit.Character, Rank[4], TileModifier.Normal),
      new SuitTile(Suit.Character, Rank[4], TileModifier.Normal),
      new SuitTile(Suit.Character, Rank[4], TileModifier.Normal),
      new SuitTile(Suit.Character, Rank[5], TileModifier.Normal),
      new SuitTile(Suit.Character, Rank[5], TileModifier.Normal),
      new SuitTile(Suit.Character, Rank[5], TileModifier.Normal),
      new SuitTile(Suit.Character, Rank[5], TileModifier.Normal),
      new SuitTile(Suit.Character, Rank[6], TileModifier.Normal),
      new SuitTile(Suit.Character, Rank[6], TileModifier.Normal),
      new SuitTile(Suit.Character, Rank[6], TileModifier.Normal),
      new SuitTile(Suit.Character, Rank[6], TileModifier.Normal),
      new SuitTile(Suit.Character, Rank[7], TileModifier.Normal),
      new SuitTile(Suit.Character, Rank[7], TileModifier.Normal),
      new SuitTile(Suit.Character, Rank[7], TileModifier.Normal),
      new SuitTile(Suit.Character, Rank[7], TileModifier.Normal),
      new SuitTile(Suit.Character, Rank[8], TileModifier.Normal),
      new SuitTile(Suit.Character, Rank[8], TileModifier.Normal),
      new SuitTile(Suit.Character, Rank[8], TileModifier.Normal),
      new SuitTile(Suit.Character, Rank[8], TileModifier.Normal),
      new SuitTile(Suit.Character, Rank[9], TileModifier.Normal),
      new SuitTile(Suit.Character, Rank[9], TileModifier.Normal),
      new SuitTile(Suit.Character, Rank[9], TileModifier.Normal),
      new SuitTile(Suit.Character, Rank[9], TileModifier.Normal),

      new SuitTile(Suit.Circle, Rank[1], TileModifier.Normal),
      new SuitTile(Suit.Circle, Rank[1], TileModifier.Normal),
      new SuitTile(Suit.Circle, Rank[1], TileModifier.Normal),
      new SuitTile(Suit.Circle, Rank[1], TileModifier.Normal),
      new SuitTile(Suit.Circle, Rank[2], TileModifier.Normal),
      new SuitTile(Suit.Circle, Rank[2], TileModifier.Normal),
      new SuitTile(Suit.Circle, Rank[2], TileModifier.Normal),
      new SuitTile(Suit.Circle, Rank[2], TileModifier.Normal),
      new SuitTile(Suit.Circle, Rank[3], TileModifier.Normal),
      new SuitTile(Suit.Circle, Rank[3], TileModifier.Normal),
      new SuitTile(Suit.Circle, Rank[3], TileModifier.Normal),
      new SuitTile(Suit.Circle, Rank[3], TileModifier.Normal),
      new SuitTile(Suit.Circle, Rank[4], TileModifier.Normal),
      new SuitTile(Suit.Circle, Rank[4], TileModifier.Normal),
      new SuitTile(Suit.Circle, Rank[4], TileModifier.Normal),
      new SuitTile(Suit.Circle, Rank[4], TileModifier.Normal),
      new SuitTile(Suit.Circle, Rank[5], TileModifier.Normal),
      new SuitTile(Suit.Circle, Rank[5], TileModifier.Normal),
      new SuitTile(Suit.Circle, Rank[5], TileModifier.Normal),
      new SuitTile(Suit.Circle, Rank[5], TileModifier.Normal),
      new SuitTile(Suit.Circle, Rank[6], TileModifier.Normal),
      new SuitTile(Suit.Circle, Rank[6], TileModifier.Normal),
      new SuitTile(Suit.Circle, Rank[6], TileModifier.Normal),
      new SuitTile(Suit.Circle, Rank[6], TileModifier.Normal),
      new SuitTile(Suit.Circle, Rank[7], TileModifier.Normal),
      new SuitTile(Suit.Circle, Rank[7], TileModifier.Normal),
      new SuitTile(Suit.Circle, Rank[7], TileModifier.Normal),
      new SuitTile(Suit.Circle, Rank[7], TileModifier.Normal),
      new SuitTile(Suit.Circle, Rank[8], TileModifier.Normal),
      new SuitTile(Suit.Circle, Rank[8], TileModifier.Normal),
      new SuitTile(Suit.Circle, Rank[8], TileModifier.Normal),
      new SuitTile(Suit.Circle, Rank[8], TileModifier.Normal),
      new SuitTile(Suit.Circle, Rank[9], TileModifier.Normal),
      new SuitTile(Suit.Circle, Rank[9], TileModifier.Normal),
      new SuitTile(Suit.Circle, Rank[9], TileModifier.Normal),
      new SuitTile(Suit.Circle, Rank[9], TileModifier.Normal),

      new SuitTile(Suit.Bamboo, Rank[1], TileModifier.Normal),
      new SuitTile(Suit.Bamboo, Rank[1], TileModifier.Normal),
      new SuitTile(Suit.Bamboo, Rank[1], TileModifier.Normal),
      new SuitTile(Suit.Bamboo, Rank[1], TileModifier.Normal),
      new SuitTile(Suit.Bamboo, Rank[2], TileModifier.Normal),
      new SuitTile(Suit.Bamboo, Rank[2], TileModifier.Normal),
      new SuitTile(Suit.Bamboo, Rank[2], TileModifier.Normal),
      new SuitTile(Suit.Bamboo, Rank[2], TileModifier.Normal),
      new SuitTile(Suit.Bamboo, Rank[3], TileModifier.Normal),
      new SuitTile(Suit.Bamboo, Rank[3], TileModifier.Normal),
      new SuitTile(Suit.Bamboo, Rank[3], TileModifier.Normal),
      new SuitTile(Suit.Bamboo, Rank[3], TileModifier.Normal),
      new SuitTile(Suit.Bamboo, Rank[4], TileModifier.Normal),
      new SuitTile(Suit.Bamboo, Rank[4], TileModifier.Normal),
      new SuitTile(Suit.Bamboo, Rank[4], TileModifier.Normal),
      new SuitTile(Suit.Bamboo, Rank[4], TileModifier.Normal),
      new SuitTile(Suit.Bamboo, Rank[5], TileModifier.Normal),
      new SuitTile(Suit.Bamboo, Rank[5], TileModifier.Normal),
      new SuitTile(Suit.Bamboo, Rank[5], TileModifier.Normal),
      new SuitTile(Suit.Bamboo, Rank[5], TileModifier.Normal),
      new SuitTile(Suit.Bamboo, Rank[6], TileModifier.Normal),
      new SuitTile(Suit.Bamboo, Rank[6], TileModifier.Normal),
      new SuitTile(Suit.Bamboo, Rank[6], TileModifier.Normal),
      new SuitTile(Suit.Bamboo, Rank[6], TileModifier.Normal),
      new SuitTile(Suit.Bamboo, Rank[7], TileModifier.Normal),
      new SuitTile(Suit.Bamboo, Rank[7], TileModifier.Normal),
      new SuitTile(Suit.Bamboo, Rank[7], TileModifier.Normal),
      new SuitTile(Suit.Bamboo, Rank[7], TileModifier.Normal),
      new SuitTile(Suit.Bamboo, Rank[8], TileModifier.Normal),
      new SuitTile(Suit.Bamboo, Rank[8], TileModifier.Normal),
      new SuitTile(Suit.Bamboo, Rank[8], TileModifier.Normal),
      new SuitTile(Suit.Bamboo, Rank[8], TileModifier.Normal),
      new SuitTile(Suit.Bamboo, Rank[9], TileModifier.Normal),
      new SuitTile(Suit.Bamboo, Rank[9], TileModifier.Normal),
      new SuitTile(Suit.Bamboo, Rank[9], TileModifier.Normal),
      new SuitTile(Suit.Bamboo, Rank[9], TileModifier.Normal),

      new HonorTile(Honor.East, TileModifier.Normal),
      new HonorTile(Honor.East, TileModifier.Normal),
      new HonorTile(Honor.East, TileModifier.Normal),
      new HonorTile(Honor.East, TileModifier.Normal),
      new HonorTile(Honor.South, TileModifier.Normal),
      new HonorTile(Honor.South, TileModifier.Normal),
      new HonorTile(Honor.South, TileModifier.Normal),
      new HonorTile(Honor.South, TileModifier.Normal),
      new HonorTile(Honor.West, TileModifier.Normal),
      new HonorTile(Honor.West, TileModifier.Normal),
      new HonorTile(Honor.West, TileModifier.Normal),
      new HonorTile(Honor.West, TileModifier.Normal),
      new HonorTile(Honor.North, TileModifier.Normal),
      new HonorTile(Honor.North, TileModifier.Normal),
      new HonorTile(Honor.North, TileModifier.Normal),
      new HonorTile(Honor.North, TileModifier.Normal),
      new HonorTile(Honor.White, TileModifier.Normal),
      new HonorTile(Honor.White, TileModifier.Normal),
      new HonorTile(Honor.White, TileModifier.Normal),
      new HonorTile(Honor.White, TileModifier.Normal),
      new HonorTile(Honor.Green, TileModifier.Normal),
      new HonorTile(Honor.Green, TileModifier.Normal),
      new HonorTile(Honor.Green, TileModifier.Normal),
      new HonorTile(Honor.Green, TileModifier.Normal),
      new HonorTile(Honor.Red, TileModifier.Normal),
      new HonorTile(Honor.Red, TileModifier.Normal),
      new HonorTile(Honor.Red, TileModifier.Normal),
      new HonorTile(Honor.Red, TileModifier.Normal),
    );
  }
}
